In [1]:
import pandas as pd

In [16]:
rna_df = pd.read_csv("HCC/Part2_BasicDataProcessingResult/LIHC__geneExp.txt",sep = '\t')

In [17]:
rna_df = rna_df.T

In [18]:
len(rna_df)

426

In [42]:
rna_df.head(4)

,0,1,2,3,4,5,6,7,8,9,...,20520,20521,20522,20523,20524,20525,20526,20527,20528,20529
GeneSymbol,?,?,?,?,?,?,?,?,?,?,...,ZWILCH,ZWINT,ZXDA,ZXDB,ZXDC,ZYG11A,ZYG11B,ZYX,ZZEF1,ZZZ3
EntrezID,100133144,100134869,10357,10431,136542,155060,26823,280660,317712,340602,...,55055,11130,7789,158586,79364,440590,79699,7791,23140,26009
TCGA-OR-A5J1-01A-11R-A29S-07,3.2661,3.9385,149.135,2034.1,0,274.255,1.4409,0,0,17.7714,...,183.958,146.974,20.6532,351.585,1050.91,0.4803,648.415,1841.02,1157.54,596.062
TCGA-OR-A5J2-01A-11R-A29S-07,2.6815,8.9948,81.0777,1304.93,0,199.302,0,0,0,0.4026,...,264.125,438.464,57.1735,279.023,2979.87,31.4052,1166.02,3059.99,1895.99,801.637

In [43]:
rna_df.reset_index(inplace = True)
rna_df.columns = rna_df.iloc[0]
rna_df = rna_df[2:]
rna_df = rna_df.rename(columns = {"GeneSymbol":"Samples"})

In [44]:
rna_df.to_csv("ACC/rna.tsv",index = False,sep = '\t')

In [20]:
mrna_df =  pd.read_csv("HCC/Part2_BasicDataProcessingResult/LIHC__miRNAExp__RPM.txt",sep = '\t')
mrna_df = mrna_df.T
mrna_df.reset_index(inplace = True)

In [21]:
len(mrna_df)

422

In [62]:
mrna_df.head(4)

,index,0,1,2,3,4,5,6,7,8,...,1860,1861,1862,1863,1864,1865,1866,1867,1868,1869
0,GeneSymbol,hsa-let-7a-1,hsa-let-7a-2,hsa-let-7a-3,hsa-let-7b,hsa-let-7c,hsa-let-7d,hsa-let-7e,hsa-let-7f-1,hsa-let-7f-2,...,hsa-mir-941-3,hsa-mir-941-4,hsa-mir-942,hsa-mir-943,hsa-mir-944,hsa-mir-95,hsa-mir-96,hsa-mir-98,hsa-mir-99a,hsa-mir-99b
1,TCGA-OR-A5J1-01A-11R-A29W-13,13476.1,26756.7,13703.3,15202.9,1963.95,1722.24,2680.78,46.1503,16790.9,...,0,0,1.76821,0.176821,0,5.83509,21.2185,119.001,522.683,61424.8
2,TCGA-OR-A5J2-01A-11R-A29W-13,4440.86,8799.33,4601.52,11209.7,1654.24,1256.68,1373.86,14.0728,2828.93,...,0,0,1.7591,0,0,15.3433,17.982,52.6754,889.521,62694.5
3,TCGA-OR-A5J3-01A-11R-A29W-13,7041.98,14003.6,7064.07,10654.2,742.691,398.813,3171.34,46.9191,13291.6,...,0,0,3.32344,0,0,15.0532,3.32344,70.3787,142.321,62730.3

In [47]:
mrna_df.columns = mrna_df.iloc[0]

In [48]:
mrna_df.head(4)

,GeneSymbol,hsa-let-7a-1,hsa-let-7a-2,hsa-let-7a-3,hsa-let-7b,hsa-let-7c,hsa-let-7d,hsa-let-7e,hsa-let-7f-1,hsa-let-7f-2,...,hsa-mir-941-3,hsa-mir-941-4,hsa-mir-942,hsa-mir-943,hsa-mir-944,hsa-mir-95,hsa-mir-96,hsa-mir-98,hsa-mir-99a,hsa-mir-99b
0,GeneSymbol,hsa-let-7a-1,hsa-let-7a-2,hsa-let-7a-3,hsa-let-7b,hsa-let-7c,hsa-let-7d,hsa-let-7e,hsa-let-7f-1,hsa-let-7f-2,...,hsa-mir-941-3,hsa-mir-941-4,hsa-mir-942,hsa-mir-943,hsa-mir-944,hsa-mir-95,hsa-mir-96,hsa-mir-98,hsa-mir-99a,hsa-mir-99b
1,TCGA-OR-A5J1-01A-11R-A29W-13,13476.1,26756.7,13703.3,15202.9,1963.95,1722.24,2680.78,46.1503,16790.9,...,0,0,1.76821,0.176821,0,5.83509,21.2185,119.001,522.683,61424.8
2,TCGA-OR-A5J2-01A-11R-A29W-13,4440.86,8799.33,4601.52,11209.7,1654.24,1256.68,1373.86,14.0728,2828.93,...,0,0,1.7591,0,0,15.3433,17.982,52.6754,889.521,62694.5
3,TCGA-OR-A5J3-01A-11R-A29W-13,7041.98,14003.6,7064.07,10654.2,742.691,398.813,3171.34,46.9191,13291.6,...,0,0,3.32344,0,0,15.0532,3.32344,70.3787,142.321,62730.3

In [49]:

mrna_df = mrna_df[1:]
mrna_df = mrna_df.rename(columns = {"GeneSymbol":"Samples"})

In [50]:
mrna_df.head(4)

,Samples,hsa-let-7a-1,hsa-let-7a-2,hsa-let-7a-3,hsa-let-7b,hsa-let-7c,hsa-let-7d,hsa-let-7e,hsa-let-7f-1,hsa-let-7f-2,...,hsa-mir-941-3,hsa-mir-941-4,hsa-mir-942,hsa-mir-943,hsa-mir-944,hsa-mir-95,hsa-mir-96,hsa-mir-98,hsa-mir-99a,hsa-mir-99b
1,TCGA-OR-A5J1-01A-11R-A29W-13,13476.1,26756.7,13703.3,15202.9,1963.95,1722.24,2680.78,46.1503,16790.9,...,0,0,1.76821,0.176821,0,5.83509,21.2185,119.001,522.683,61424.8
2,TCGA-OR-A5J2-01A-11R-A29W-13,4440.86,8799.33,4601.52,11209.7,1654.24,1256.68,1373.86,14.0728,2828.93,...,0,0,1.7591,0,0,15.3433,17.982,52.6754,889.521,62694.5
3,TCGA-OR-A5J3-01A-11R-A29W-13,7041.98,14003.6,7064.07,10654.2,742.691,398.813,3171.34,46.9191,13291.6,...,0,0,3.32344,0,0,15.0532,3.32344,70.3787,142.321,62730.3
4,TCGA-OR-A5J4-01A-11R-A29W-13,11043.4,22197.7,11170.2,14483.1,3901.53,1904.87,2856.99,84.7534,19160.7,...,0,0,9.43481,0,1.11938,8.95507,35.1806,73.7194,843.216,67547.3

In [51]:
mrna_df.to_csv("ACC/mirna.tsv",index = False,sep = '\t')

In [52]:
len(mrna_df)

79

In [53]:
meth_df =  pd.read_csv("ACC/Part3_AdvancedDataProcessingResult/ACC__methylation_450__TSS200-TSS1500__Both.txt",sep = '\t')
meth_df = meth_df.T
meth_df.reset_index(inplace = True)

In [54]:
meth_df.columns = meth_df.iloc[0]
meth_df = meth_df[2:]
meth_df = meth_df.rename(columns = {"GeneSymbol":"Samples"})

In [55]:
meth_df.head(4)

,Samples,WASH5P,OR4F5,MIR1977,LOC643837,LINC00115,FAM41C,FLJ39609,SAMD11,KLHL17,...,H2AB1,H2AB3,FUNDC2,BRCC3,MTCP1,CMC4,VBP1,RAB39B,CLIC2,TMLHE
2,TCGA-OR-A5J1-01A-11D-A29J-05,0.0975656,0.710663,0.106165,0.0204862,0.0204862,0.785968,0.786421,0.0655286,0.525882,...,0.944692,0.944692,0.0842993,0.0433652,0.0433652,0.0433652,0.0625957,0.108488,0.159999,0.335454
3,TCGA-OR-A5J2-01A-11D-A29J-05,0.0773728,0.234449,0.119204,0.0194322,0.0194322,0.38298,0.320797,0.0573512,0.431292,...,0.953963,0.953963,0.58213,0.442495,0.442495,0.442495,0.288474,0.501144,0.0670165,0.30792
4,TCGA-OR-A5J3-01A-11D-A29J-05,0.062482,0.419968,0.140401,0.0196624,0.0196624,0.630712,0.490206,0.060129,0.461492,...,0.97084,0.97084,0.0896332,0.155532,0.155532,0.155532,0.142311,0.105516,0.828915,0.253469
5,TCGA-OR-A5J4-01A-11D-A29J-05,0.101781,0.293361,0.106486,0.0268422,0.0268422,0.453072,0.662908,0.0623472,0.495345,...,0.962939,0.962939,0.484479,0.53417,0.53417,0.53417,0.217052,0.35401,0.207763,0.268401

In [27]:
meth_df.to_csv("ACC/meth.tsv",index = False,sep = '\t')

In [28]:
copynumber_df =  pd.read_csv("HCC/Part2_BasicDataProcessingResult/LIHC__copyNumber.txt",sep = '\t')

In [29]:
copynumber_df.head(5)

,GeneSymbol,Chromosome,Strand,TCGA-2V-A95S-01A-11D-A36W-01,TCGA-2V-A95S-10D-01D-A36Z-01,TCGA-2Y-A9GS-01A-12D-A381-01,TCGA-2Y-A9GS-10A-01D-A384-01,TCGA-2Y-A9GT-01A-11D-A381-01,TCGA-2Y-A9GT-10A-01D-A384-01,TCGA-2Y-A9GU-01A-11D-A381-01,...,TCGA-ZP-A9D4-01A-11D-A36W-01,TCGA-ZS-A9CD-01A-11D-A36W-01,TCGA-ZS-A9CD-10A-01D-A36Z-01,TCGA-ZS-A9CE-01A-11D-A36W-01,TCGA-ZS-A9CE-10A-01D-A36Z-01,TCGA-ZS-A9CF-01A-11D-A381-01,TCGA-ZS-A9CF-02A-11D-A381-01,TCGA-ZS-A9CF-10A-01D-A384-01,TCGA-ZS-A9CG-01A-11D-A36W-01,TCGA-ZS-A9CG-10A-01D-A36Z-01
0,DDX11L1,CHR1,+,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,WASH7P,CHR1,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,FAM138A,CHR1,-,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,OR4F5,CHR1,+,-0.0577,0.0539,-0.3162,-0.0244,-0.0128,-0.3185,-0.0434,...,-0.0119,-0.0464,-0.5659,-0.7795,0.0001,0.0037,0.561,0.0152,0.4146,0.738
4,LOC729737,CHR1,-,-0.0577,0.0539,-0.3162,-0.0244,-0.0128,-0.3185,-0.0434,...,-0.0119,-0.0464,0.0072,0.0557,0.0001,0.0037,0.561,0.0152,-0.0243,NaN

In [30]:
copynumber_df = copynumber_df.T
copynumber_df.reset_index(inplace = True)

In [31]:
copynumber_df.head(10)

,index,0,1,2,3,4,5,6,7,8,...,24906,24907,24908,24909,24910,24911,24912,24913,24914,24915
0,GeneSymbol,DDX11L1,WASH7P,FAM138A,OR4F5,LOC729737,LOC100132287,OR4F29,OR4F16,LOC100133331,...,TTTY4B,TTTY4C,TTTY17C,GOLGA2P3Y,CSPG4P1Y,CDY1,TTTY3,SPRY3,VAMP7,IL9R
1,Chromosome,CHR1,CHR1,CHR1,CHR1,CHR1,CHR1,CHR1,CHR1,CHR1,...,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY
2,Strand,+,-,-,+,-,+,+,-,-,...,-,-,-,+,+,+,+,+,+,+
3,TCGA-2V-A95S-01A-11D-A36W-01,NaN,NaN,NaN,-0.0577,-0.0577,-0.0577,-0.0577,-0.0577,-0.0577,...,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,NaN,NaN,NaN
4,TCGA-2V-A95S-10D-01D-A36Z-01,NaN,NaN,NaN,0.0539,0.0539,0.0539,0.0539,0.0539,0.0539,...,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,NaN,NaN,NaN
5,TCGA-2Y-A9GS-01A-12D-A381-01,NaN,NaN,NaN,-0.3162,-0.3162,0.1354,0.1354,0.1354,0.1354,...,-0.257,-0.257,-0.257,-0.257,-0.257,-0.257,-0.257,NaN,NaN,NaN
6,TCGA-2Y-A9GS-10A-01D-A384-01,NaN,NaN,NaN,-0.0244,-0.0244,-0.0244,-0.0244,-0.0244,-0.0244,...,-0.4436,-0.4436,-0.4436,-0.4436,-0.4436,-0.4436,-0.0492,NaN,NaN,NaN
7,TCGA-2Y-A9GT-01A-11D-A381-01,NaN,NaN,NaN,-0.0128,-0.0128,-0.0128,-0.0128,-0.0128,-0.0128,...,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,NaN,NaN,NaN
8,TCGA-2Y-A9GT-10A-01D-A384-01,NaN,NaN,NaN,-0.3185,-0.3185,-0.3185,-0.3185,-0.3185,-0.3185,...,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,NaN,NaN,NaN
9,TCGA-2Y-A9GU-01A-11D-A381-01,NaN,NaN,NaN,-0.0434,-0.0434,-0.0434,-0.0434,-0.0434,-0.0434,...,-3.764,-3.764,-2.3486,-2.3486,-2.3486,-3.2224,-3.2224,NaN,NaN,NaN

In [32]:
copynumber_df.columns = copynumber_df.iloc[0]

In [33]:
copynumber_df.head(10)

,GeneSymbol,DDX11L1,WASH7P,FAM138A,OR4F5,LOC729737,LOC100132287,OR4F29,OR4F16,LOC100133331,...,TTTY4B,TTTY4C,TTTY17C,GOLGA2P3Y,CSPG4P1Y,CDY1,TTTY3,SPRY3,VAMP7,IL9R
0,GeneSymbol,DDX11L1,WASH7P,FAM138A,OR4F5,LOC729737,LOC100132287,OR4F29,OR4F16,LOC100133331,...,TTTY4B,TTTY4C,TTTY17C,GOLGA2P3Y,CSPG4P1Y,CDY1,TTTY3,SPRY3,VAMP7,IL9R
1,Chromosome,CHR1,CHR1,CHR1,CHR1,CHR1,CHR1,CHR1,CHR1,CHR1,...,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY,CHRY
2,Strand,+,-,-,+,-,+,+,-,-,...,-,-,-,+,+,+,+,+,+,+
3,TCGA-2V-A95S-01A-11D-A36W-01,NaN,NaN,NaN,-0.0577,-0.0577,-0.0577,-0.0577,-0.0577,-0.0577,...,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,NaN,NaN,NaN
4,TCGA-2V-A95S-10D-01D-A36Z-01,NaN,NaN,NaN,0.0539,0.0539,0.0539,0.0539,0.0539,0.0539,...,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,NaN,NaN,NaN
5,TCGA-2Y-A9GS-01A-12D-A381-01,NaN,NaN,NaN,-0.3162,-0.3162,0.1354,0.1354,0.1354,0.1354,...,-0.257,-0.257,-0.257,-0.257,-0.257,-0.257,-0.257,NaN,NaN,NaN
6,TCGA-2Y-A9GS-10A-01D-A384-01,NaN,NaN,NaN,-0.0244,-0.0244,-0.0244,-0.0244,-0.0244,-0.0244,...,-0.4436,-0.4436,-0.4436,-0.4436,-0.4436,-0.4436,-0.0492,NaN,NaN,NaN
7,TCGA-2Y-A9GT-01A-11D-A381-01,NaN,NaN,NaN,-0.0128,-0.0128,-0.0128,-0.0128,-0.0128,-0.0128,...,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,NaN,NaN,NaN
8,TCGA-2Y-A9GT-10A-01D-A384-01,NaN,NaN,NaN,-0.3185,-0.3185,-0.3185,-0.3185,-0.3185,-0.3185,...,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,NaN,NaN,NaN
9,TCGA-2Y-A9GU-01A-11D-A381-01,NaN,NaN,NaN,-0.0434,-0.0434,-0.0434,-0.0434,-0.0434,-0.0434,...,-3.764,-3.764,-2.3486,-2.3486,-2.3486,-3.2224,-3.2224,NaN,NaN,NaN

In [34]:
copynumber_df = copynumber_df[3:]
copynumber_df = copynumber_df.rename(columns = {"GeneSymbol":"Samples"})

In [36]:
copynumber_df.dropna(axis = 1, inplace = True)

In [37]:
copynumber_df.head(10)

,Samples,LOC100288069,LINC00115,LOC643837,FAM41C,SAMD11,NOC2L,PLEKHN1,PERM1,ISG15,...,GOLGA2P3Y,DAZ3,BPY2C,TTTY4,TTTY4B,TTTY4C,GOLGA2P3Y,CSPG4P1Y,CDY1,TTTY3
3,TCGA-2V-A95S-01A-11D-A36W-01,-0.0577,-0.0577,-0.0577,-0.0577,-0.0577,-0.0577,-0.0577,-0.0577,-0.0577,...,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997,-0.3997
4,TCGA-2V-A95S-10D-01D-A36Z-01,0.0539,0.0539,0.0539,0.0539,0.0539,0.0539,0.0539,0.0539,0.0539,...,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475,-0.3475
5,TCGA-2Y-A9GS-01A-12D-A381-01,0.1354,0.1354,0.1354,0.1354,0.1354,0.1354,0.1354,0.1354,0.1354,...,-0.257,-0.257,-0.257,-0.257,-0.257,-0.257,-0.257,-0.257,-0.257,-0.257
6,TCGA-2Y-A9GS-10A-01D-A384-01,-0.0244,-0.0244,-0.0244,-0.0244,-0.0244,-0.0244,-0.0244,-0.0244,-0.0244,...,-0.4436,-0.4436,-0.4436,-0.4436,-0.4436,-0.4436,-0.4436,-0.4436,-0.4436,-0.0492
7,TCGA-2Y-A9GT-01A-11D-A381-01,-0.0128,-0.0128,-0.0128,-0.0128,-0.0128,-0.0128,-0.0128,-0.0128,-0.0128,...,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281,-0.5281
8,TCGA-2Y-A9GT-10A-01D-A384-01,-0.3185,0.376,0.376,0.376,0.376,0.376,0.376,0.376,0.376,...,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939,-0.3939
9,TCGA-2Y-A9GU-01A-11D-A381-01,-0.0434,-0.0434,-0.0434,-0.0434,-0.0434,-0.0434,-0.0434,-0.0434,-0.0434,...,-2.9422,-3.764,-3.764,-3.764,-3.764,-3.764,-2.3486,-2.3486,-3.2224,-3.2224
10,TCGA-2Y-A9GV-01A-11D-A381-01,-0.0462,-0.0462,-0.0462,-0.0462,-0.0462,-0.0462,-0.0462,-0.0462,-0.0462,...,-3.6413,-4.255,-4.255,-4.255,-4.255,-4.255,-2.7798,-2.7798,-3.7976,-3.7976
11,TCGA-2Y-A9GV-10A-01D-A384-01,-0.125,-0.125,-0.125,-0.125,-0.125,-0.125,-0.125,-0.125,-0.125,...,-2.7495,-4.2295,-4.2295,-4.2295,-4.2295,-4.2295,-2.7515,-2.7515,-3.7,-3.7
12,TCGA-2Y-A9GW-01A-11D-A381-01,-0.1075,-0.1075,-0.1075,-0.1075,-0.1075,-0.1075,-0.1075,-0.1075,-0.1075,...,-0.4976,-0.4976,-0.4976,-0.4976,-0.4976,-0.4976,-0.4976,-0.4976,-0.4976,-0.4976

In [38]:
copynumber_df.to_csv("HCC/copynumber.tsv",index = False,sep = '\t')